# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SegSam
                                 A QGIS plugin
 generate poly using SAM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-26
        copyright            : (C) 2025 by Ofer Butbega
        email                : bkst.dev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import sys
import os

# Fix for QGIS environment where sys.stderr/stdout might be None
# This must be done before importing any other modules that might use numpy
if sys.stderr is None:
    sys.stderr = open(os.devnull, 'w')
if sys.stdout is None:
    sys.stdout = open(os.devnull, 'w')


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SegSam class from file SegSam.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_osam import SegSam
    return SegSam(iface)
